name: Add Commit For An Issue

on:
    issues:
        types: [opened]

env:
    OWNER_AND_REPO: ${{ github.repository.full_name }}
    ISSUE_NUMBER: ${{ github.repository.open_issues }}


jobs:
    add-default-message:
        runs-on: ubuntu-latest
        steps:
            - name: Add default message
              env:
                GITHUB_TOKEN: ${{ github.token }}
              run: |
                gh api \
                --method POST \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2026-03-10" \
                /repos/${{ env.OWNER_AND_REPO }}/issues/${{ env.ISSUE_NUMBER }}/comments \
                -f 'body=Me too'