name: Add Comment For An Issue

on:
  issues:
    types: [opened]

jobs:
  add-default-message:
    runs-on: ubuntu-latest
    steps:
      - name: Add default message
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Lấy trực tiếp từ context của event
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$REPO/issues/$ISSUE_NUMBER/comments \
            -f "body=Me too"