# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

run-name: "Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}"

on:
  push:
    branches: [ "master" ]

env:
  name: "manh"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    # steps:
    # - uses: actions/checkout@v4
    # - name: Set up JDK 17
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'
    #     cache: maven
    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml
    steps:
      - run: echo 'Hi ${{ env.name }}'
      - run: echo 'Hi ${{ env.name }}'
        env:
          name: "Luat"
      # Repository secret
      - run: echo 'Print Secret Key ${{ secrets.MY_SECRET }}'
      # Enviroment secret
      - run: echo 'MY DB PASSWORD FROM ENV DEV ${{ secrets.DB_PASSWORD }}'
      - run: echo 'MY DB URL FROM ENV DEV ${{ vars.DB_URL }}'