name: Hello World

# overwrite the commit message
run-name: "Run name with commit ${{ github.event.head_commit.message }}"

# event to trigger the workflows
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
# All the job run in pararell if not depend on each others
jobs:
    # the first job run on ubuntu OS
    say-hello:
        runs-on: ubuntu-latest
        # define all the step in this job
        steps:
            # - name: "Checkout Code"
            #   uses: actions/checkout@v4
            
            - name: "Say hello"
              run: echo "hello bro!"
              shell: bash

            - name: "Github event"
              run: echo '${{ toJson(github.event) }}'
    
    #  the second job run on ubuntu OS
    say-goodbye:
        needs: [say-hello]
        runs-on: ubuntu-latest

        steps:
            - name: "Say goodbye"
              run: echo "Goodbye bro!"
              shell: bash
              