name: Hello World

# overwrite the commit message
run-name: "Run name with commit: ${{ github.event.head_commit.message }}"

# event to trigger the workflows
on:
    workflow_dispatch:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

env:
    MY_NAME: "manh"

# All the job run in pararell if not depend on each others
jobs:
    # the first job run on ubuntu OS
    say-hello:
        runs-on: ubuntu-latest
        # define all the step in this job
        outputs:
            who_to_greet: ${{ steps.define_who_to_greet.outputs.person_name }}
        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v4
            
            - id: "define_who_to_greet"
              name: "Say hello"
              run: |
                echo "hello bro!"
                echo "person_name=brian" >> $GITHUB_OUTPUT
              shell: bash

            - name: "Execute something in external"
              run: |
                ls -l
                chmod +x action.sh
                ./action.sh

            - name: "Print my Name"
              run: echo $MY_NAME
              env:
                MY_NAME: "brian" 

    
    #  the second job run on ubuntu OS
    say-goodbye:
        needs: [say-hello]
        runs-on: ubuntu-latest

        steps:
            - name: "Say goodbye"
              run: echo "Goodbye bro ${{ needs.say-hello.outputs.who_to_greet }} !"
              shell: bash

            - name: "Print my Name"
              run: echo $MY_NAME
              